# Generated by Django 4.0.6 on 2022-07-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(default='EMPTY_IMG', max_length=300)),
                ('source', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
